#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_MESSAGE_LENGTH 2000
#define MAX_USERNAME_LENGTH 30
#define MAX_PASSWORD_LENGTH 30
#define MAX_CITY_LENGTH 50
#define MAX_AREA_LENGTH 100
#define MAX_CITY_LIST_LENGTH 500
#define MAX_AREA_LIST_LENGTH 200
#define MAX_PARKING_LENGTH 50
#define MAX_DATE_TIME_LENGTH 30

#endif 
